// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeLC_c_kBlgEn9HrGxU8XGMwnCMq4gB3g',
    appId: '1:290137948559:web:5caa82b7226c2e962b0bfa',
    messagingSenderId: '290137948559',
    projectId: 'rickysmartphone-4504a',
    authDomain: 'rickysmartphone-4504a.firebaseapp.com',
    storageBucket: 'rickysmartphone-4504a.appspot.com',
    measurementId: 'G-7W1C7MKLE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAGe8kmPJK4HF3N-MdFY20VswlSQKp-00',
    appId: '1:290137948559:android:da4bbb89d3819eea2b0bfa',
    messagingSenderId: '290137948559',
    projectId: 'rickysmartphone-4504a',
    storageBucket: 'rickysmartphone-4504a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZmafKa-DW7NC22E2ccUuoeSQNI9nsOXU',
    appId: '1:290137948559:ios:408ccb26c9a8ee322b0bfa',
    messagingSenderId: '290137948559',
    projectId: 'rickysmartphone-4504a',
    storageBucket: 'rickysmartphone-4504a.appspot.com',
    androidClientId: '290137948559-9an8udu8c4900lvm50pv28chomipa4eg.apps.googleusercontent.com',
    iosClientId: '290137948559-r707mrdu37ae71oupkeugfdm416d8pvk.apps.googleusercontent.com',
    iosBundleId: 'com.kardusinfo.rickyMobile',
  );
}
